name: Deploy to CloudHub

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:

jobs:
  Deploy to CloudHub:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
      
      - name: Configure setting.xml with Anypoint Platform credentials
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          output_file: .m2/settings.xml
          servers: >
            [
              {
                "id": "anypoint-exchange-v2",
                "username": "${{ secrets.ANYPOINT_USERNAME }}",
                "password": "${{ secrets.ANYPOINT_PASSWORD }}"
              }
            ]
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      
      - name: Deploy with Maven
        env:
          MULE_ENV: dev
          MULE_SERVER: cloudhub
          MULE_REGION: us-east-2
          MULE_WORKERS: 1
          MULE_WORKERTYPE: MICRO
          MULE_APPNAME: Spending API
          
        run: |
          mvn clean deploy -DskipTests -DmuleDeploy -Dmule.env=$MULE_ENV -Dmule.key=${{ secrets.MULE_KEY }} -Dmule.server=$MULE_SERVER 
          -Dmule.region=$MULE_REGION  -Dmule.workers=$MULE_WORKERS -Dmule.workerType=$MULE_WORKERTYPE -Dmule.appName=$MULE_APPNAME -s .m2/settings.xml
