# This is a basic workflow to help you get started with Actions

name: Deploy with settings.xml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
          
  createSettings:
    name: Create settings.xml
    runs-on: ubuntu-latest
    steps:
    
    - name: Get access token
      run: |
        echo "ACCESS_TOKEN=$(curl -s "https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token" -X POST -H "Content-Type: application/json" -d "{\"grant_type\": \"client_credentials\", \"client_id\": \"${{ secrets.APP_CLIENT_ID }}\", \"client_secret\": \"${{ secrets.APP_CLIENT_SECRET }}\"}" | sed -n 's|.*"access_token":"\([^"]*\)".*|\1|p')" >> $GITHUB_ENV
      shell: bash 
    - name: Configure setting.xml with Anypoint Platform credentials
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        output_file: settings.xml
        repositories: >
          [
            {
              "id": "MuleRepository",
              "name": "MuleRepository",
              "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "anypoint-exchange-v2",
              "username": "~~~Token~~~",
              "password": "${{ env.ACCESS_TOKEN }}"
            },
            {
              "id": "mulesoft-releases",
              "username": "~~~Token~~~",
              "password": "${{ env.ACCESS_TOKEN }}"
            },
            {
              "id": "MuleRepository",
              "username": "${{ secrets.REPO_USERNAME }}",
              "password": "${{ secrets.REPO_PASSWORD }}"
            },
            {
              "id": "github",
              "username": "${{ secrets.USERNAME }}",
              "password": "${{ secrets.GIT_TOKEN }}"
            },
            {
              "id": "Repository",
              "username": "${{ secrets.USERNAME }}",
              "password": "${{ secrets.PASSWORD }}"
            }
          ]
    - name: Upload settings.xml
      uses: actions/upload-artifact@v2
      with:
        name: settings
        path: settings.xml
        
  test:
    name: Test
    needs: [createSettings, deployCH]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test Mule App
        uses: manuelrbrizi/deploy-to-cloudhub-action/test@main
        with:
          testParams: -Dmule.env=dev -Dmule.key=${{ secrets.MULE_KEY }}
          
  #testPublish:
  #  name: Publish test report
  #  needs: [test]
    # The type of runner that the job will run on
  #  runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
  #  steps:
  #    - name: Download tests.xml
  #      uses: actions/download-artifact@v2
  #      with:
  #        name: tests
  #        
   #   - name: Publish Unit Test Results
   #     uses: EnricoMi/publish-unit-test-result-action@v1
   #     with:
   #       files: tests.xml
          
  updateVersion:
    name: Update release version
    needs: [sonarQubeTest] #[sonarQubeTest]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test Mule App
        uses: manuelrbrizi/deploy-to-cloudhub-action/updateVersion@main
          
  deployXC:
    name: Deploy to Exchange
    needs: [updateVersion]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: deployToExchange
        uses: manuelrbrizi/deploy-to-cloudhub-action/deployToExchange@main
        with:
          projectName: spending-eapi-impl
          
  deployCH:
    name: Deploy to CloudHub
    needs: [createSettings]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: deployToCloudhub
        uses: manuelrbrizi/deploy-to-cloudhub-action/deployToCloudhub@main
        with:
          deployParams: -Dmule.env=dev -Dmule.key=${{ secrets.MULE_KEY }} -Dserver=cloudhub -Dregion=us-east-2 -Dworkers=1 -DworkerType=MICRO -DappName=spending-git -Danypoint.platform.client_id=${{ secrets.ANYPOINT_CLIENT_ID }} -Danypoint.platform.client_secret=${{ secrets.ANYPOINT_CLIENT_SECRET }} -Denvironment=Playground
          versionUpdated: false
          
  deployApiManager:
    name: Deploy to API Manager
    needs: [deployXC]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: deployToAPIManager
        uses: manuelrbrizi/deploy-to-cloudhub-action/apiManager@main
        with:
          ORGID: ${{ secrets.ORGID }}
          ENVID: ${{ secrets.ENVID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          
  newmanTesting:
    name: Newman Integration testing
    needs: [deployCH]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: newmanIntegrationTesting
        uses: manuelrbrizi/deploy-to-cloudhub-action/newman@main
        with:
          collectionName: postman_collection.json
          
  sonarQubeTest:
    name: SonarQube code testing
    needs: [test]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: sonarQubeTesting
        uses: manuelrbrizi/deploy-to-cloudhub-action/sonarqube@main
        with:
          sourcesPath: src/main/mule
